version: "3.9"

services:
    pgdatabase:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        expose:
            - 5432
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data/:rw


    www:
        build:
            context: .
            dockerfile: ./Docker/django/Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./lowfoundAI:/app/lowfoundAI
        expose:
            - 8000
        depends_on:
            - pgdatabase

    nginx:
        build:
            context: .
            dockerfile: ./Docker/nginx/Dockerfile
        ports:
            - 80:80
        depends_on:
            - www

volumes:
    pgdata:
